version: "3.6"

services:
    app:
        build:
            context: ../
            dockerfile: Dockerfile.Development
        ports:
            - "3000:3000"
            - "9229:9229"
        command:
            - yarn
            - "start:debug"
        volumes:
            - ../:/app
